const frases = [
    "Vai la cara...", 
    "Vou jogar o saci na graxa.", 
    "O dominó vai cair...", 
    "Estou com um prego enfiado no cú!", 
    "O que está acontecendo com o motor da kombi?", 
    "Viajou para Dourados.", 
    "Painel de jipe.", 
    "Painel de avião.", 
    "Chupa-cabra automático.", 
    "Muita gente é bom só pra cortar cana.", 
    "Me fala uma coisa gratuita que presta?", 
    "A culpa é do Ricardo...", 
    "Eu não quero saber... Eu quero que você venha com uma solução!", 
    "É só uma sugestão...", 
    "No no No no No no No no No no No no No no No no", 
    "Se eu [qualquer besteira] ..., vai funcionar?", 
    "Mas se até ontem funcionava...?", 
    "O que está acontecendo com o NOSSO sistema de [qualquer coisa]?", 
    "Faz favor...?", 
    "O que é @Column?", 
    "As galinhas estão botando?", 
    "Bode véio...", 
    "Queimar lata.", 
    "E se processar em paralelo?", 
    "Isso só aconteceu depois que mudou pro Sql Server.", 
    "Ah, cara... Me desculpa...", 
    "Ahrhrhrh!!!!", 
    "O que aconteceu com a carroça?", 
    "Uhhhhhhhhhhhhhhh, meu amigo!", 
    "Tudo fimose?", 
    "É que ela é mais.... mais....", 
    "Doguiva.", 
    "Miniiiiiiiiiiinu!!", 
    "Tamo tudo dentro do mesmo buteco.", 
    "Aí derrubou o revórvi no barro!", 
    "O que este telefone está fazendo ali?", 
    "O problema foi a mudança pra Algar?", 
    "Vocês são o futuro!", 
    "Eu ja fui assalariado...", 
    "Táááá!", 
    "Tedeu?", 
    "Poblema", 
    "Parabéns!", 
    "Cê qué me fudê?", 
    "Rodomoinho..", 
    "E aí? Descobriu alguma coisa?", 
    "Fonciona!", 
    "Eu vou jogar gasolina em você e você que se apague!", 
    "Mo carro.",
    "Vou bater na gorduchinha!", 
    "Éhhh! Não é bem assim. VAMO LÁ !!! [explicação] ...", 
    "Você foi bruto agora.", 
    "Seu tênis está sujo.", 
    "Nasal.", 
    "Os gerentes querem bater punheta com os diretores.", 
    "Eu até chupo, mas não dou a bunda não.", 
    "Teoricamente...", 
    "Síndrome do Fantástico.", 
    "Cadê o Hélio? É por isso que o departamento está funcionando.", 
    "Ou você senta no meu colo, ou eu sento no seu. Escolhe!", 
    "Aloo, Everton? Beleza, cara?", 
    "E aí? Correndo igual um leão pra não morrer igual um veado?", 
    "Que nem que a gente tava conversando...", 
    "Uéhhhhh!", 
    "Bom dia, meninos e meninas!", 
    "Bom dia, meu presidente. Você está onde? Preciso de alguém para pagar o meu almoço.", 
    "Porque, igual que você falou...", 
    "Caaara!!!", 
    "Agência que os Vingadores trabalham, a SHIT...", 
    "Comprei um Mac, formatei e instalei o Windows.", 
    "Tá errado!", 
    "Vocês estão construindo bueiro.", 
    "Tudo dentro?", 
    "Você conseguiu dar uma olhada naquele [email, poblema]?", 
    "Cooperatieva", 
    "Não. Mas, você tem que ver que...", 
    "Nã Não. Mas é aí que tá!", 
    "Dezasseis", 
    "Dezanove", 
    "Tá tudo parado? Eu vou no dentista!", 
    "Pega o sapo, corta e engole.", 
    "Teve atualização no sistema?", 
    "Seguro de vida é que nem árabe: você pode ter 4, 5 mulheres, só tem que ter o dinheiro para pagar.", 
    "Aaaaaparentemente...", 
    "Porque, parecer que realmente...", 
    "IIIIIIsso!", 
    "Sr. Orinaaaaaaaaaldo. O Homem da camisa número 10.", 
    "Firme e forte, como prego na polenta?", 
    "Deixa eu ver com o Aguinaldo.", 
    "Perfeito!", 
    "Uma coisa é uma coisa, outra coisa é outra coisa.", 
    "O que acontece é o seguinte...", 
    "Em todo lugar funciona, só aqui que não funciona?", 
    "Voce já experimentou levar um tiro na testa?", 
    "Eu confio... desconfiando!", 
    "Você tem que fazer do limão a limonada.", 
    "Deixa eu te fazer uma peeeeergunta.", 
    "Não confunda alhos com bugalhos.", 
    "Por que o que que acontece...", 
    "Quando vocês vao pentear isso aqui?", 
    "Como está este timaço?", 
    "Se você der uma olhada da forma que foi feita...", 
    "Não, mas, calma aí...", 
    "Nois é brega, mas nois vai ser chic!", 
    "Nem que o Saci cruze a perna.", 
    "Se chover carroça não vai faltar emprego pra ele!", 
    "Treme beiço...", 
    "Se eu não tiver um cú para aprovar este troço de 30 mil (compra do RiverBed), pode me manda embora!", 
    "Tô pagando a marmita e é outro que tá comendo.", 
    "Eu vou tirar o macaco do colo do cara pra colocar no meu?", 
    "Conversinha minhoca. Sem pé nem cabeça!", 
    "As 'mulhé' senta e chora, e os 'home' corre pro banheiro.", 
    "Gaivota azul.", 
    "Hoje é aniversário do Taiada. Palmas pro Taiada!", 
    "É muita gente respirando poder...", 
    "É ovo no Japão e outro no Brasil, mas sai da mesma galinha.", 
    "Ahrhrhrh!!!! Que cara burro!!", 
    "Não, esse cara é muito burro!", 
    "[Alguém] Não dá para fazer isto porque ... [Boss] Está fazendo barranco, não quero barranco!", 
    "Quem não é gerente é pé de chinelo!", 
    "Você está chicoteando cavalo morto.", 
    "O cara é durão? Esquenta, dá na oreia pra ver se ele canta. Igual ferro!", 
    "A sorte acompanha os audazes.", 
    "O cara é igual a pardal. Se soltar ele voa, se apertar ele caga.", 
    "Chassi de grilo.", 
    "Informática é bom quando funciona.", 
    "Estou engessando a perna que nem foi quebrada ainda.", 
    "O nosso pessoal tem que entender que...", 
    "Se você não se cuidar, quando tiver minha idade vai estar igual uma pipa véia.", 
    "Não fica nivooso!", 
    "Para, para. Deixa eu falar / deixa eu molha o bico...", 
    "... tedeeeo ...", 
    "O filme muda mas os atores são os mesmos.", 
    "A granada não é pra matar o inimigo. É pra arrancar uma perna, um braço e baixar a moral da tropa inteira.", 
    "Síndrome do soldado ferido. O cara além de não fazer porra nenhuma, ainda atrapalha os outros.", 
    "Se você não sabe, já fala!", 
    "Olha só que interessante,... [qualquer besteira depois]", 
    "Método da lavadeira: torcendo pra dar certo!", 
    "A democracia é a melhor e a pior coisa do mundo...", 
    "Não me interessa se o pato é macho... eu quero o ovo!", 
    "Você fez isso ai no powerpoint? (perguntando de um pdf feito no latex)", 
    "Curinga no jogo de truco...(serve pra nada)", 
    "Você tem a mão erótica: onde coloca, fode!", 
    "Não, por isso que a gente tá falando... (igual a gente tá falando)", 
    "Vou lançar um desafio para você!", 
    "No meio de macacos, faça macaquices!", 
    "Enquanto a gente trabalha de graça, o diretor ganha de graça.", 
    "Então, vamos supor...", 
    "Hélio, você é o gerentão Hélio...", 
    "O cara quer fazer um strip, mas vem só de cueca!", 
    "Jabuti em cima da árvore! Ele não subiu sozinho, alguém colocou ele lá ou foi enchente.", 
    "Vai na fé que vai dá tudo certo. (toma uma decisão cegamente)", 
    "Qual a dificuldade?", 
    "Pensar faz parte do seu trabalho!", 
    "Pra ir pro céu, você tem que morrer...", 
    "Se eu tô pagando o leite, eu vou comer a mãe.", 
    "Quem tem medo de cagar, não come.", 
    "Mandar demanda pra terceiro é o mesmo que mandar um filho pra Febem. Em dois dias chega tudo fudido, daí você perde um mês educando ele novamente.", 
    "Não entra nesta 'seara'.", 
    "A gente só se caga na calça quando está com infecção intestinal, os caras parecem criança.", 
    "Não adianta costurar o paciente se tem outro puxando a faca.", 
    "Vai balançar a sua rede que a minha o vento balança.", 
    "Os caras cagam lá e enfiam a bosta no nosso cú aqui.", 
    "Nossa comunicação não está boa. Você não me escuta! Eu não aguento mais, eu vou jogar a toalha.", 
    "Não basta ser esperto. Tem que estar esperto!", 
    "Aqui a gente tem que andar com a bunda na parede!", 
    "O bom é melhor que o ótimo!", 
    "Me sinto como um hetero na boate gay. [tá todo mundo querendo me foder]", 
    "Até um chute na bunda te leva pra frente!", 
    "De acasalamento de muriçoca à atracamento de navio, o cara entende de tudo!", 
    "Não se empilha promessas!", 
    "Primeiro apaga o incêndio, depois faz a perícia.", 
    "O cara é mais grosso que cano de passar bosta.", 
    "Em uma chuva de pica, senta logo na primeira que cair! Se ficar escolhendo muito, pode ser que apareça outra ainda maior!", 
    "Calma...não precisa ficar com medo do rastro da onça!", 
    "Pato bota ovo porque sabe o cú que tem!", 
    "Jacaré come lata porque sabe o cú que tem!", 
    "Faz o bolo e confeita com bosta.", 
    "...que pessoalzinho mais 'sem expediente'!", 
    "O tempo é igual pra todos, só a prioridade que muda.", 
    "Nós estamos mais sujos que puleiro de papagaio.", 
    "Você tá preocupado com o quê? Tá parecendo um cachorro na canoa!", 
    "Se você deixar a bunda pra cima, os caras vão entrar com tudo!", 
    "'...eu era estagiário e o cara me mandava comprar cigarro, longe, umas cinco quadras...e eu ia a pé. Quando eu voltava, o cara me agradecia dizendo: você vai longe, menino!!'", 
    "Eu consigo ser mais produtivo em uma casinha de cachorro na Sibéria do que neste escritório.", 
    "Cada cachorro que lamba a sua caceta.", 
    "Quero ver carpir!", 
    "Vai dar uma de virgem na zona?", 
    "Você é um imã de atrair nó cego!", 
    "Tá mais parado que saci de patinete...", 
    "Tudo que faz tem um cisco no cú.", 
    "Tem que ensinar, senão coloca a camisinha no dedão do pé.", 
    "Onde se ganha o pão não se come a carne.", 
    "Vem comigo que você brilha!", 
    "É muito tiro pra pouca pombinha.", 
    "Isso parece uma sanfona velha: quanto mais mexe, mais desafina!", 
    "...bota a pica na mesa!!!", 
    "A gente tem que aproveitar bem a vida, porque depois que morrer, vamo ficar um bom tempo morto.", 
    "Gestor jardineiro: O galho que se destaca sempre é podado.", 
    "Mais vale um sistema miando do que um gestor latindo.", 
    "A cabeça tá na sombra, mas o rabo tá no formigueiro!", 
    "O cara vende o sofá, mas não discute o relacionamento!", 
    "A 3 melhores coisas da vida são: dinheiro, mulher e bixo de pé. Não adianta ter dinheiro e mulher se o bixo não estiver de pé!", 
    "Felizes são aqueles que não são tristes!", 
    "A Kombi embicou...", 
    "Dor demais, dói bastante!", 
    "Mulher feia é igual a mulher bonita, só que feia.", 
    "Uns gostam do olho, outros da remela.", 
    "Três coisas na vida não tem solução: folga no volante da Kombi, vazamento no motor do Pérk e catinga de cú.", 
    "Quem paga com banana, contrata macaco.", 
    "Quando não achares a saída, saia pela entrada.", 
    "Não faça na vida pública o que vc faz na privada.", 
    "Vamos devagar, porque a gente tem pressa!", 
    "Quinta-feira é igual calcinha: não é o que você quer, mas tá quase lá...", 
    "Voce tá querendo tirar o cú de banda?", 
    "O cara tá trabalhando de terninho mas a barriga tá roncado!", 
    "Tem verdade que não serve pra qualquer ouvido.", 
    "A força que ele bate é proporcional ao desconhecimento sobre o assunto. Pra esconder a ignorância!", 
    "Argumento de jumento é coice!", 
    "Antigamente empresas procuravam bons funcionários pra trabalhar. Hoje o funcionário está desesperado atrás de emprego. O funcionário assina a carteira de nariz fechado sabendo a merda que está fazendo.", 
    "Se você quer, você pede...eu tenho umas bolas aqui, mas não são de cristal!", 
    "Isso parece conversa de bêbado com delegado.", 
    "O cara quer pegar a galinha fazendo 'Oooowwww'.", 
    "Andar para trás é como andar para frente, só que de costas...", 
    "Não sou a favor nem contra, muito pelo contrário!", 
    "Eu prefiro ficar amarelo de vergonha por ter dito um não, do que vermelho de raiva por ter dito um sim!", 
    "De onde nada se espera é que não se pode esperar nada mesmo.", 
    "As vezes eu prefiro a paz do que a razão!", 
    "Cateto fora do bando é comida de onça.", 
    "Não morra antes da morte.", 
    "Novas maneiras de fazer velhas coisas.", 
    "Todos os nossos sistemas automatizados são manuais.", 
    "A criatividade é filha da dificuldade.", 
    "...é mais velho que jumento emprestado.", 
    "Quem tem tempo caga longe!", 
    "Tá bonito hein? Tá no pintão de rico!", 
    "Time de várzea joga mais de uma partida por dia.", 
    "Não importa o tamanho da vara, o que importa é a mágica que ela faz!", 
    "Claro que isso tá errado, mas pode!", 
    "Quem mandou arrumar o buraco? Era só pra colocar uma propaganda dizendo que está arrumado!", 
    "Garrafa que carrega gasolina uma vez, nunca perde o cheiro.", 
    "Gato que levou tijolada não dorme em olaria!", 
    "Quem gosta de briga de onça é capivara.", 
    "No balançar da carroça é que as abóboras se ajeitam.", 
    "Vai pescar? Pacu pequeno, minhoca. Pacu grande, mandioca.", 
    "Eu sonho e você não dorme!", 
    "Isso tá mais confuso que reunião de paraguaio!", 
    "É a mesma coisa que contar dinheiro na frente de pobre!", 
    "Não adianta tentar ser freira em baile de puta...", 
    "Se eu comer uma sopa de letrinhas eu consigo cagar um argumento melhor que o seu!", 
    "'Fulano' é tão indeciso, que se na casa dele tiver dois banheiros, ele caga no corredor!", 
    "O futuro não importa, o que importa é daqui pra frente...", 
    "Nós temos mais sorte do que juízo!", 
    "Tá tudo certo e nada resolvido...", 
    "'Fulano' é um cara estrumado!", 
    "(certeza) é macuco no borná! (bornal)", 
    "É o satanaz de rodinha...", 
    "Oôopáh", 
    "Muda o mosquito, mas a merda é a mesma.", 
    "A pessoa que tem a língua boa normalmente tem o ouvido ruim.", 
    "O cara é bom, mas ele é sério! (as aventuras de boas pessoas no mundo mágico da sarrada)", 
    "Por trás de uma demanda, bate um coração!", 
    "Na hora do crau, o dente amolece", 
    "Todo problema que começa com 'EU' é 'SEU'!", 
    "Não me peça pra fazer em tempo récorde o que você não conseguiu planejar em tempo hábil!", 
    "...isso já tá durando mais do que esperança de pobre!", 
    "O jornal sempre embrulha o peixe no dia seguinte.", 
    "Todo mundo só vê as pinga que eu tomo, mas ninguém sabe dos tombo que eu levo...", 
    "Nós somos donos da lagoa e estamos perdendo para os sapos.", 
    "Boteco sem pinga é como um jardim sem flor.", 
    "Boca de viola.", 
    "Em briga de saci, qualquer chute é voadora.", 
    "O amor é cego, mas o casamento devolve a visão.", 
    "Acabou a cerveja, acabou a amizade.", 
    "O diabo não é mais esperto, ele é mais velho!", 
    "Isso é mais inútil do que cinzeiro em moto.", 
    "É mais inútil que muro alto em cemitério.", 
    "Saliva não se arquiva!", 
    "É mais facil ensinar papagaio velho a falar...", 
    "Tem gente que é trouxa até na hora de ser esperto.", 
    "Em casa de saci, uma calça dá pra dois.", 
    "Não me importa a cor do gato, me importa que ele cace o rato!", 
    "Fica com essas conversinhas que logo você vai ficar queimado na rodinha.", 
    "As melancias são acomodadas conforme o caminhão anda.", 
    "Se colocar a cenoura muito longe, o burro desanima!", 
    "Olhou, sorriu? Mandioca no bombril!", 
    "Dinheiro na mão, calcinha no chão.", 
    "Quando o cú tá cheio, toda goiaba tem bicho.", 
    "Você é o túnel no final de alguma luz!", 
    "O cara quer o cú e já quer raspado!", 
    "Vai rasgando que eu vou costurando!", 
    "É melhor ser cú de baleia, do que olho de grilo.", 
    "Se mudar a cor da grama, a pessoa passa fome.", 
    "Já comi peixe com mais espinhos.", 
    "O cara nem caiu e já está deitado.", 
    "Jacaré que fica parado vira bolsa.", 
    "Está mais escondido que ponta de durex...", 
    "O que aduba a vida são as merdas que a gente faz!", 
    "Você nunca vai ver uma abelha explicando pra uma mosca que mel é melhor que bosta!", 
    "A gente é muito bom de velório, mas é ruim de enterro.", 
    "De perto todo mundo é feio!", 
    "A cada pena puxada sai uma galinha!", 
    "Quanto mais o tambor está cheio, menos ele faz barulho.", 
    "Quanto mais levantar o tapete, mais gente cai.", 
    "Quanto mais fundo enterrar, menos vai feder.", 
    "O louco da caneta...", 
    "Insanidade diária.", 
    "Não tem o quê fazer: tá alto pra capinar, tá baixo pra roçar, tá molhado pra pôr fogo...e o cigarro tá acabando.", 
    "...aí é outro chopp, outra batatinha.", 
    "O certo do anzol é ser torto."
];

var frase = frases[Math.floor(Math.random() * (frases.length+1))];